#!/bin/bash

# Ensure script is being run by root!
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 
  exit 1
fi

# enable colorful terminal
sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' ~/.bashrc

# update the machine
apt update
apt -y dist-upgrade

# periodic security updated
echo '' >> /etc/crontab
echo '@hourly root apt update && unattended-upgrade' | tee -a /etc/crontab

# Install some useful stuff
apt -y install man-db vim git ufw htop iotop bash-completion iftop unattended-upgrades
dpkg-reconfigure bash-completion

apt -y autoremove

# enable the firewall (you'll have to open where applicable)
ufw enable

# use strong certs
#rm -rf ~/.ssh
mv .ssh .ssh.bak
mkdir ~/.ssh
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -q -N ''
ssh-keygen -t ecdsa -b 521 -f ~/.ssh/id_ecdsa -q -N ''
ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -q -N ''

#rm /etc/ssh/ssh_host_*
mkdir /etc/ssh/bak
mv /etc/ssh/ssh_host_* /etc/ssh/bak/
ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -q -N ''
ssh-keygen -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_key -q -N ''
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -q -N ''

echo 'KexAlgorithms curve25519-sha256@libssh.org' | tee -a /etc/ssh/sshd_config
service ssh restart

